GET http://localhost:5000/api/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTJiZmRjMy00MjkxLTQ3NmQtYjFlNy0zN2RiMTg2Yjc4MDAiLCJpYXQiOjE3NzQ2MTM4MTIsImV4cCI6MTc3NDYxNDcxMn0.McX1tTvt2afbp7-HNFFc6sgKYjJxbnfiWpcNp-GjD4Y
